# Generated by Django 4.2.7 on 2024-07-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
